# =======================================================
#                       LIBRARIES                       
# =======================================================

add_subdirectory ("libs/database")

# =======================================================

add_executable (windows-event-log-collector main.cpp)

# =======================================================
#                          HEADERS
# =======================================================

target_link_libraries(windows-event-log-collector 
    PRIVATE
        database_lib
        wevtapi   
)

# =======================================================
#                          TESTS
# =======================================================

